version: '3.5'

services:
  db:
    image: postgres:11.7-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123

  api:
    build: ./
    command: /bin/bash Dockerfiles/docker-entrypoint.sh
    volumes:
      - ./:/app
      - dependencies_cache:/app_dependencies/bundle
    ports:
      - "3003:3003"
    depends_on:
      - db
      - redis
      - broker_app
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/manager_development
      - TEST_DATABASE_URL=postgresql://postgres:123@db:5432/manager_test
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SECRET_KEY=b3902a3c892b23a1f6ef0e3a7e145024ea9166844bfce78c21f192d
      - REDIS_URL=redis://redis:6379/0
      - PROD_DATABASE_URL=
      - METRIC_UI_PACT_URI=http://broker_app:80/pacts/provider/metric-provider/consumer/metric-consumer/latest
    networks:
     - default
     - manager_net

  redis:
    image: redis:5.0.3
    ports:
      - "127.0.0.1:6379:6379"

  broker_app:
    image: dius/pact-broker
    links:
      - db
    ports:
      - "80:80"
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: 123
      PACT_BROKER_DATABASE_HOST: db
      PACT_BROKER_DATABASE_NAME: postgres
    networks:
      - default
      - manager_net

volumes:
  db_data:
  dependencies_cache:

networks:
  manager_net:
    name: manager
