version: '3.5'

services:
  api:
    build:
      target: builder
    command: /bin/bash Dockerfiles/test-entrypoint.sh
    environment:
      - RAILS_ENV=test
      - PATTERN=/app/spec/swagger/**/*_spec.rb
