default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

  <%
    test_url = ENV.fetch("TEST_DATABASE_URL")
    parallel_url = URI.parse(test_url)
    parallel_url.path = "#{parallel_url.path}#{ENV.fetch('TEST_ENV_NUMBER', 4)}"
  %>
test:
  <<: *default
  url: <%= parallel_url.to_s %>

production:
  <<: *default
  url: <%= ENV.fetch("PROD_DATABASE_URL") %>
